name: wa-update

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  schedule:
    - cron: '0,30 * * * *'

jobs:
  wa-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}

      - name: Setup GIT
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Get npm cache directory
        id: npm-cache
        run: |
          echo "dir=$(npm config get cache)" >> $GITHUB_OUTPUT
      - name: Setup npm cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        run: npm ci || npm install

      - name: Fix husky
        run: chmod ug+x .husky/pre-commit

      - name: Check Updates
        id: update
        run: npm run wa-update
        env:
          WA_COMMIT: true

      - name: Git Status
        if: ${{ steps.update.outputs.hasChanges == 'true' }}
        run: git status

      - name: Remove untracked files
        if: ${{ steps.update.outputs.hasChanges == 'true' }}
        run: git clean -fd

      - name: Release
        if: ${{ steps.update.outputs.hasChanges == 'true' }}
        run: npm run release -- --ci -i patch

      - name: Discord Notification (Outdated)
        uses: sarisia/actions-status-discord@v1
        if: ${{ steps.update.outputs.hasOutdated == 'true' }}
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          nodetail: true
          color: 0xCB2431
          title: Outdated WhatsApp WEB versions
          description: |
            Some versions of WhatsApp WEB doesn't work anymore.
            Outdated versions: `${{ join(fromJSON(steps.update.outputs.outdated), '`, `') }}`

      - name: Discord Notification (New)
        uses: sarisia/actions-status-discord@v1
        if: ${{ steps.update.outputs.hasNewVersion == 'true' }}
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          nodetail: true
          color: 0x28A745
          title: New version for WhatsApp WEB!
          description: |
            A new version of WhatsApp WEB has just been released.
            Version Number: `${{ fromJSON(steps.update.outputs.version) }}`
